# Generated by Django 5.2.8 on 2025-12-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_rename_organization_contact_organization_and_more"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="contacts", to="tags.tag"),
        ),
    ]
