# Generated by Django 5.2.8 on 2025-12-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="leads", to="tags.tag"),
        ),
    ]
