# Generated by Django 5.2.8 on 2025-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="contract",
            field=models.FileField(blank=True, null=True, upload_to="contracts/"),
        ),
    ]
